---
title: "Assignment 1: Introduction"
author: "Kendall Fitzgerald"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: In terms of R, my previous experience has been one undergraduate course learning the basics of the language. I have also taken a few undergraduate course in basic GIS components that incorporated Python, as well. However, all of these courses were five years ago and unfortunately I haven't done much with them since then. I have not used Git extensively before but I'm eager to learn more about it and become more comfortable with R. 

2. Are there any components of the course about which you feel confident?

> Answer: Because I have a little bit of experience with coding language as a concept, I feel confident with the idea that even if I don't grasp lessons right away I will become more comfortable with them the more I practice and revisit concepts I don't understand. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: Because I don't have professional experience with R and I haven't touched it in awhile, I'm apprehensive about the stress of not fully grasping a concept before moving on to the next lesson. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/kendall-fitzgerald/EDE_Fall2024/blob/main/Assignments/KendallFitzgerald_A01_Introduction.Rmd

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
